{
 "title": "Proxmox E1",
 "description": "Resources available on Proxmox Clusters EdgeUno",
 "tags": [
  "proxmox",
  "viz",
  "resources"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Cluster Mexico QRO1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "USED OF CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "PVE001",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=", "value": "PVE001-QRO1" }
     ]
    },
    {
     "alias": "PVE002",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=", "value": "pve002-qro1" }
     ]
    }
   ]
  },
  {
   "title": "Total Traffic on Cluster (IN)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "IN",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "nics",
     "select": [
      [
       { "params": [ "netin" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "LXC Containers",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vmid" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "nodename" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "query": "SELECT mean(\"cpus\") AS \"Procesors\", mean(\"maxmem\") /1073741824 AS \"RAM\", max(\"maxdisk\") /1073741824 AS \"DISK\" FROM \"system\" WHERE (\"object\" = 'lxc') AND $timeFilter GROUP BY \"vmid\", \"host\", \"nodename\" LIMIT 1",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Procesors" ], "type": "alias" }
      ],
      [
       { "params": [ "maxmem" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "RAM" ], "type": "alias" }
      ],
      [
       { "params": [ "maxdisk" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "DISK" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "lxc" }
     ]
    }
   ]
  },
  {
   "title": "Total Traffic on Cluster (OUT)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "IN",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "nics",
     "select": [
      [
       { "params": [ "netout" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FREE RAM",
   "type": "stat",
   "description": "Ram FREE per node",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "PVE001",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "memfree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "PVE001-QRO1" }
     ]
    },
    {
     "alias": "PVE002",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "memfree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve002-qro1" }
     ]
    }
   ]
  },
  {
   "title": "KVM VPS",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vmid" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "nodename" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "query": "SELECT mean(\"cpus\") AS \"Procesors\", mean(\"maxmem\") /1073741824 AS \"RAM\", max(\"maxdisk\") /1073741824 AS \"DISK\" FROM \"system\" WHERE (\"object\" = 'lxc') AND $timeFilter GROUP BY \"vmid\", \"host\", \"nodename\" LIMIT 1",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Procesors" ], "type": "alias" }
      ],
      [
       { "params": [ "maxmem" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "RAM" ], "type": "alias" }
      ],
      [
       { "params": [ "maxdisk" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "DISK" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "qemu" },
      { "condition": "AND", "key": "vmid", "operator": "<", "value": "1000" }
     ]
    }
   ]
  },
  {
   "title": "TOTAL VPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vmid" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "select": [
      [
       { "params": [ "vmid" ], "type": "field" },
       { "params": [ " / vmid" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "vmid", "operator": "<", "value": "1000" }
     ]
    }
   ]
  },
  {
   "title": "FREE STORAGE",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "CEPHFS Storage",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "avail" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "storages" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "rbd" }
     ]
    },
    {
     "alias": "FREE LVM LOCAL STORAGE",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "avail" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "storages" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "lvmthin" }
     ]
    }
   ]
  },
  { "title": "Cluster Istanbul", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "USED OF CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "PVE001",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=", "value": "pve001-ist" }
     ]
    }
   ]
  },
  {
   "title": "Total Traffic on Cluster (IN)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "IN",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "nics",
     "select": [
      [
       { "params": [ "netin" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "LXC Containers",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vmid" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "nodename" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "query": "SELECT mean(\"cpus\") AS \"Procesors\", mean(\"maxmem\") /1073741824 AS \"RAM\", max(\"maxdisk\") /1073741824 AS \"DISK\" FROM \"system\" WHERE (\"object\" = 'lxc') AND $timeFilter GROUP BY \"vmid\", \"host\", \"nodename\" LIMIT 1",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Procesors" ], "type": "alias" }
      ],
      [
       { "params": [ "maxmem" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "RAM" ], "type": "alias" }
      ],
      [
       { "params": [ "maxdisk" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "DISK" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "lxc" }
     ]
    }
   ]
  },
  {
   "title": "Total Traffic on Cluster (OUT)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "IN",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "nics",
     "select": [
      [
       { "params": [ "netout" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FREE RAM",
   "type": "stat",
   "description": "Ram FREE per node",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "PVE001",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "memfree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve001-ist" }
     ]
    }
   ]
  },
  {
   "title": "KVM VPS",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vmid" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "nodename" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "query": "SELECT mean(\"cpus\") AS \"Procesors\", mean(\"maxmem\") /1073741824 AS \"RAM\", max(\"maxdisk\") /1073741824 AS \"DISK\" FROM \"system\" WHERE (\"object\" = 'lxc') AND $timeFilter GROUP BY \"vmid\", \"host\", \"nodename\" LIMIT 1",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Procesors" ], "type": "alias" }
      ],
      [
       { "params": [ "maxmem" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "RAM" ], "type": "alias" }
      ],
      [
       { "params": [ "maxdisk" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "DISK" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "qemu" },
      { "condition": "AND", "key": "vmid", "operator": "<", "value": "1000" }
     ]
    }
   ]
  },
  {
   "title": "TOTAL VPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vmid" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "select": [
      [
       { "params": [ "vmid" ], "type": "field" },
       { "params": [ " / vmid" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "vmid", "operator": "<", "value": "1000" }
     ]
    }
   ]
  },
  {
   "title": "FREE STORAGE",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "FREE NFS STORAGE",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "avail" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "storages" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "glusterfs" }
     ]
    }
   ]
  },
  { "title": "Cluster Miami", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "USED OF CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "PVE001",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=", "value": "pve001-mia" }
     ]
    },
    {
     "alias": "PVE002",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=", "value": "pve002-mia" }
     ]
    }
   ]
  },
  {
   "title": "Total Traffic on Cluster (IN)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "IN",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "nics",
     "select": [
      [
       { "params": [ "netin" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "LXC Containers",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vmid" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "nodename" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "query": "SELECT mean(\"cpus\") AS \"Procesors\", mean(\"maxmem\") /1073741824 AS \"RAM\", max(\"maxdisk\") /1073741824 AS \"DISK\" FROM \"system\" WHERE (\"object\" = 'lxc') AND $timeFilter GROUP BY \"vmid\", \"host\", \"nodename\" LIMIT 1",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Procesors" ], "type": "alias" }
      ],
      [
       { "params": [ "maxmem" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "RAM" ], "type": "alias" }
      ],
      [
       { "params": [ "maxdisk" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "DISK" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "lxc" }
     ]
    }
   ]
  },
  {
   "title": "Total Traffic on Cluster (OUT)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "IN",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "nics",
     "select": [
      [
       { "params": [ "netout" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FREE RAM",
   "type": "stat",
   "description": "Ram FREE per node",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "PVE001",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "memfree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve001-mia" }
     ]
    },
    {
     "alias": "PVE002",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "memfree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve002-mia" }
     ]
    }
   ]
  },
  {
   "title": "KVM VPS",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vmid" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "nodename" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Procesors" ], "type": "alias" }
      ],
      [
       { "params": [ "maxmem" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "RAM" ], "type": "alias" }
      ],
      [
       { "params": [ "maxdisk" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "DISK" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "qemu" },
      { "condition": "AND", "key": "vmid", "operator": "<", "value": "1000" }
     ]
    }
   ]
  },
  {
   "title": "TOTAL VPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vmid" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "select": [
      [
       { "params": [ "vmid" ], "type": "field" },
       { "params": [ " / vmid" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "vmid", "operator": "<", "value": "1000" }
     ]
    }
   ]
  },
  {
   "title": "FREE STORAGE",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "FREE CephFS STORAGE",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "avail" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "storages" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cephfs" }
     ]
    },
    {
     "alias": "FREE GlusterFS STORAGE",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "avail" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "storages" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "glusterfs" }
     ]
    }
   ]
  },
  { "title": "Cluster Bogota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "USED OF CPU",
   "type": "stat",
   "description": "ALL CPUS ON BOGOTA",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "PVE001",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=", "value": "pve001" }
     ]
    },
    {
     "alias": "PVE002",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=", "value": "pve002" }
     ]
    },
    {
     "alias": "PVE003",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=", "value": "pve003" }
     ]
    }
   ]
  },
  {
   "title": "Total Traffic on Cluster (IN)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "IN",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "nics",
     "select": [
      [
       { "params": [ "netin" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "LXC Containers",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vmid" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "nodename" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "query": "SELECT mean(\"cpus\") AS \"Procesors\", mean(\"maxmem\") /1073741824 AS \"RAM\", max(\"maxdisk\") /1073741824 AS \"DISK\" FROM \"system\" WHERE (\"object\" = 'lxc') AND $timeFilter GROUP BY \"vmid\", \"host\", \"nodename\" LIMIT 1",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Procesors" ], "type": "alias" }
      ],
      [
       { "params": [ "maxmem" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "RAM" ], "type": "alias" }
      ],
      [
       { "params": [ "maxdisk" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "DISK" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "lxc" }
     ]
    }
   ]
  },
  {
   "title": "Total Traffic on Cluster (OUT)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "IN",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "nics",
     "select": [
      [
       { "params": [ "netout" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FREE RAM",
   "type": "stat",
   "description": "Ram FREE per node",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "PVE001",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "memfree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve001" }
     ]
    },
    {
     "alias": "PVE002",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "memfree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve002" }
     ]
    },
    {
     "alias": "PVE003",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "memfree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve003" }
     ]
    }
   ]
  },
  {
   "title": "KVM VPS",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vmid" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "nodename" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Procesors" ], "type": "alias" }
      ],
      [
       { "params": [ "maxmem" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "RAM" ], "type": "alias" }
      ],
      [
       { "params": [ "maxdisk" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "DISK" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "qemu" },
      { "condition": "AND", "key": "vmid", "operator": "<", "value": "1000" }
     ]
    }
   ]
  },
  {
   "title": "TOTAL VPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vmid" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "select": [
      [
       { "params": [ "vmid" ], "type": "field" },
       { "params": [ " / vmid" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "vmid", "operator": "<", "value": "1000" }
     ]
    }
   ]
  },
  {
   "title": "STORAGE STATUS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "FREE NFS STORAGE",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "avail" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "storages" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "nfs" }
     ]
    },
    {
     "alias": "FREE SSD STORAGE",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "avail" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "storages" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "lvm" }
     ]
    },
    {
     "alias": "FREE HDD STORAGE",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "avail" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "storages" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "lvm" }
     ]
    }
   ]
  },
  { "title": "Cluster Lima", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "USED OF CPU (Total x node 40)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "PVE001",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=", "value": "pve001-lim" }
     ]
    },
    {
     "alias": "PVE002",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=", "value": "pve001-lim" }
     ]
    }
   ]
  },
  {
   "title": "Total Traffic on Cluster (IN)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "IN",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "nics",
     "select": [
      [
       { "params": [ "netin" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "LXC Containers",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vmid" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "nodename" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "query": "SELECT mean(\"cpus\") AS \"Procesors\", mean(\"maxmem\") /1073741824 AS \"RAM\", max(\"maxdisk\") /1073741824 AS \"DISK\" FROM \"system\" WHERE (\"object\" = 'lxc') AND $timeFilter GROUP BY \"vmid\", \"host\", \"nodename\" LIMIT 1",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Procesors" ], "type": "alias" }
      ],
      [
       { "params": [ "maxmem" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "RAM" ], "type": "alias" }
      ],
      [
       { "params": [ "maxdisk" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "DISK" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "lxc" }
     ]
    }
   ]
  },
  {
   "title": "Total Traffic on Cluster (OUT)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "IN",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "nics",
     "select": [
      [
       { "params": [ "netout" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FREE RAM",
   "type": "stat",
   "description": "Ram FREE per node",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "PVE001",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "memfree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve001-lim" }
     ]
    },
    {
     "alias": "PVE002",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "memfree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve002-lim" }
     ]
    }
   ]
  },
  {
   "title": "VPS KVM",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vmid" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "nodename" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "query": "SELECT mean(\"cpus\") AS \"Procesors\", mean(\"maxmem\") /1073741824 AS \"RAM\", max(\"maxdisk\") /1073741824 AS \"DISK\" FROM \"system\" WHERE (\"object\" = 'lxc') AND $timeFilter GROUP BY \"vmid\", \"host\", \"nodename\" LIMIT 1",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Procesors" ], "type": "alias" }
      ],
      [
       { "params": [ "maxmem" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "RAM" ], "type": "alias" }
      ],
      [
       { "params": [ "maxdisk" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "DISK" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "qemu" },
      { "condition": "AND", "key": "vmid", "operator": "<", "value": "1000" }
     ]
    }
   ]
  },
  {
   "title": "TOTAL VPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vmid" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "select": [
      [
       { "params": [ "vmid" ], "type": "field" },
       { "params": [ " / vmid" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "vmid", "operator": "<", "value": "1000" }
     ]
    }
   ]
  },
  {
   "title": "STORAGE STATUS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "FREE NFS STORAGE",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "avail" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "storages" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "glusterfs" }
     ]
    }
   ]
  },
  { "title": "Cluster Chile", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "USED OF CPU (Total x node 40)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "PVE001",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=", "value": "pve001-scl1" }
     ]
    },
    {
     "alias": "PVE002",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=", "value": "pve002-scl1" }
     ]
    }
   ]
  },
  {
   "title": "Total Traffic on Cluster (IN)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "IN",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "nics",
     "select": [
      [
       { "params": [ "netin" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "LXC Containers",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vmid" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "nodename" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "query": "SELECT mean(\"cpus\") AS \"Procesors\", mean(\"maxmem\") /1073741824 AS \"RAM\", max(\"maxdisk\") /1073741824 AS \"DISK\" FROM \"system\" WHERE (\"object\" = 'lxc') AND $timeFilter GROUP BY \"vmid\", \"host\", \"nodename\" LIMIT 1",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Procesors" ], "type": "alias" }
      ],
      [
       { "params": [ "maxmem" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "RAM" ], "type": "alias" }
      ],
      [
       { "params": [ "maxdisk" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "DISK" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "lxc" }
     ]
    }
   ]
  },
  {
   "title": "Total Traffic on Cluster (OUT)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "IN",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "nics",
     "select": [
      [
       { "params": [ "netout" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FREE RAM",
   "type": "stat",
   "description": "Ram FREE per node",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "PVE001",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "memfree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve001-scl1" }
     ]
    },
    {
     "alias": "PVE002",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "memfree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve002-scl1" }
     ]
    }
   ]
  },
  {
   "title": "VPS KVM",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vmid" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "nodename" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "query": "SELECT mean(\"cpus\") AS \"Procesors\", mean(\"maxmem\") /1073741824 AS \"RAM\", max(\"maxdisk\") /1073741824 AS \"DISK\" FROM \"system\" WHERE (\"object\" = 'lxc') AND $timeFilter GROUP BY \"vmid\", \"host\", \"nodename\" LIMIT 1",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Procesors" ], "type": "alias" }
      ],
      [
       { "params": [ "maxmem" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "RAM" ], "type": "alias" }
      ],
      [
       { "params": [ "maxdisk" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "DISK" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "qemu" },
      { "condition": "AND", "key": "vmid", "operator": "<", "value": "1000" }
     ]
    }
   ]
  },
  {
   "title": "TOTAL VPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 91 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vmid" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "select": [
      [
       { "params": [ "vmid" ], "type": "field" },
       { "params": [ " / vmid" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "vmid", "operator": "<", "value": "1000" }
     ]
    }
   ]
  },
  {
   "title": "STORAGE STATUS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "FREE NFS STORAGE",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "avail" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "storages" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "glusterfs" }
     ]
    }
   ]
  },
  { "title": "Cluster Argentina", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "USED OF CPU",
   "type": "stat",
   "description": "ALL CPUS ON BOGOTA",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 99 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "PVE001",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=", "value": "pve001-eze1" }
     ]
    },
    {
     "alias": "PVE002",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=", "value": "pve002-eze1" }
     ]
    },
    {
     "alias": "PVE003",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve003-eze1" }
     ]
    }
   ]
  },
  {
   "title": "Total Traffic on Cluster (IN)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "IN",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nics",
     "select": [
      [
       { "params": [ "netin" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "LXC Containers",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vmid" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "nodename" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "query": "SELECT mean(\"cpus\") AS \"Procesors\", mean(\"maxmem\") /1073741824 AS \"RAM\", max(\"maxdisk\") /1073741824 AS \"DISK\" FROM \"system\" WHERE (\"object\" = 'lxc') AND $timeFilter GROUP BY \"vmid\", \"host\", \"nodename\" LIMIT 1",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Procesors" ], "type": "alias" }
      ],
      [
       { "params": [ "maxmem" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "RAM" ], "type": "alias" }
      ],
      [
       { "params": [ "maxdisk" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "DISK" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "lxc" }
     ]
    }
   ]
  },
  {
   "title": "Total Traffic on Cluster (OUT)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "IN",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "nics",
     "select": [
      [
       { "params": [ "netout" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FREE RAM",
   "type": "stat",
   "description": "Ram FREE per node",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "PVE001",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "memfree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve001-eze1" }
     ]
    },
    {
     "alias": "PVE002",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "memfree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve002-eze1" }
     ]
    },
    {
     "alias": "PVE003",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "memfree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve003-eze1" }
     ]
    }
   ]
  },
  {
   "title": "KVM VPS",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vmid" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "nodename" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "query": "SELECT mean(\"cpus\") AS \"Procesors\", mean(\"maxmem\") /1073741824 AS \"RAM\", max(\"maxdisk\") /1073741824 AS \"DISK\" FROM \"system\" WHERE (\"object\" = 'lxc') AND $timeFilter GROUP BY \"vmid\", \"host\", \"nodename\" LIMIT 1",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Procesors" ], "type": "alias" }
      ],
      [
       { "params": [ "maxmem" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "RAM" ], "type": "alias" }
      ],
      [
       { "params": [ "maxdisk" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "DISK" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "qemu" },
      { "condition": "AND", "key": "vmid", "operator": "<", "value": "1000" }
     ]
    }
   ]
  },
  {
   "title": "TOTAL VPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 107 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vmid" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "select": [
      [
       { "params": [ "vmid" ], "type": "field" },
       { "params": [ " / vmid" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "vmid", "operator": "<", "value": "1000" }
     ]
    }
   ]
  },
  {
   "title": "STORAGE STATUS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "FREE RBD STORAGE",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "avail" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "storages" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "rbd" }
     ]
    }
   ]
  },
  { "title": "Cluster RIO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 } },
  {
   "title": "USED OF CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 115 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "PVE001",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=", "value": "pve001-rio1" }
     ]
    },
    {
     "alias": "PVE002",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=", "value": "pve002-rio1" }
     ]
    },
    {
     "alias": "PVE003",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=", "value": "pve003-rio1" }
     ]
    }
   ]
  },
  {
   "title": "Total Traffic on Cluster (IN)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "IN",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "nics",
     "select": [
      [
       { "params": [ "netin" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "LXC Containers",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vmid" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "nodename" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "query": "SELECT mean(\"cpus\") AS \"Procesors\", mean(\"maxmem\") /1073741824 AS \"RAM\", max(\"maxdisk\") /1073741824 AS \"DISK\" FROM \"system\" WHERE (\"object\" = 'lxc') AND $timeFilter GROUP BY \"vmid\", \"host\", \"nodename\" LIMIT 1",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Procesors" ], "type": "alias" }
      ],
      [
       { "params": [ "maxmem" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "RAM" ], "type": "alias" }
      ],
      [
       { "params": [ "maxdisk" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "DISK" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "lxc" }
     ]
    }
   ]
  },
  {
   "title": "Total Traffic on Cluster (OUT)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "IN",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "nics",
     "select": [
      [
       { "params": [ "netout" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FREE RAM",
   "type": "stat",
   "description": "Ram FREE per node",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "PVE001",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "memfree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve001-rio1" }
     ]
    },
    {
     "alias": "PVE002",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "memfree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve002-rio1" }
     ]
    },
    {
     "alias": "PVE003",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "memfree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve003-rio1" }
     ]
    }
   ]
  },
  {
   "title": "KVM VPS",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vmid" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "nodename" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "query": "SELECT mean(\"cpus\") AS \"Procesors\", mean(\"maxmem\") /1073741824 AS \"RAM\", max(\"maxdisk\") /1073741824 AS \"DISK\" FROM \"system\" WHERE (\"object\" = 'lxc') AND $timeFilter GROUP BY \"vmid\", \"host\", \"nodename\" LIMIT 1",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Procesors" ], "type": "alias" }
      ],
      [
       { "params": [ "maxmem" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "RAM" ], "type": "alias" }
      ],
      [
       { "params": [ "maxdisk" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "DISK" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "qemu" },
      { "condition": "AND", "key": "vmid", "operator": "<", "value": "1000" }
     ]
    }
   ]
  },
  {
   "title": "TOTAL VPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 123 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vmid" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "select": [
      [
       { "params": [ "vmid" ], "type": "field" },
       { "params": [ " / vmid" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "vmid", "operator": "<", "value": "1000" }
     ]
    }
   ]
  },
  {
   "title": "STORAGE STATUS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "FREE GLUSTER STORAGE",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "avail" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "storages" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "glusterfs" }
     ]
    },
    {
     "alias": "FREE NFS STORAGE",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "avail" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "storages" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "nfs" }
     ]
    }
   ]
  },
  { "title": "Cluster SP4 (Seaborn)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 } },
  {
   "title": "USED OF CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 131 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "PVE001",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=", "value": "PVE001-SP4" }
     ]
    },
    {
     "alias": "PVE002",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=", "value": "PVE002-SP4" }
     ]
    },
    {
     "alias": "PVE003",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=", "value": "pve003-sp4" }
     ]
    }
   ]
  },
  {
   "title": "Total Traffic on Cluster (IN)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "IN",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "nics",
     "select": [
      [
       { "params": [ "netin" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "LXC Containers",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vmid" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "nodename" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "query": "SELECT mean(\"cpus\") AS \"Procesors\", mean(\"maxmem\") /1073741824 AS \"RAM\", max(\"maxdisk\") /1073741824 AS \"DISK\" FROM \"system\" WHERE (\"object\" = 'lxc') AND $timeFilter GROUP BY \"vmid\", \"host\", \"nodename\" LIMIT 1",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Procesors" ], "type": "alias" }
      ],
      [
       { "params": [ "maxmem" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "RAM" ], "type": "alias" }
      ],
      [
       { "params": [ "maxdisk" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "DISK" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "lxc" }
     ]
    }
   ]
  },
  {
   "title": "Total Traffic on Cluster (OUT)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "IN",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "nics",
     "select": [
      [
       { "params": [ "netout" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FREE RAM",
   "type": "stat",
   "description": "Ram FREE per node",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "PVE001",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "memfree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "PVE001-SP4" }
     ]
    },
    {
     "alias": "PVE002",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "memfree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "PVE002-SP4" }
     ]
    },
    {
     "alias": "PVE003",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "memfree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve003-sp4" }
     ]
    }
   ]
  },
  {
   "title": "KVM VPS",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vmid" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "nodename" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "query": "SELECT mean(\"cpus\") AS \"Procesors\", mean(\"maxmem\") /1073741824 AS \"RAM\", max(\"maxdisk\") /1073741824 AS \"DISK\" FROM \"system\" WHERE (\"object\" = 'lxc') AND $timeFilter GROUP BY \"vmid\", \"host\", \"nodename\" LIMIT 1",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Procesors" ], "type": "alias" }
      ],
      [
       { "params": [ "maxmem" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "RAM" ], "type": "alias" }
      ],
      [
       { "params": [ "maxdisk" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "DISK" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "qemu" },
      { "condition": "AND", "key": "vmid", "operator": "<", "value": "1000" }
     ]
    }
   ]
  },
  {
   "title": "TOTAL VPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 139 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vmid" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "select": [
      [
       { "params": [ "vmid" ], "type": "field" },
       { "params": [ " / vmid" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "vmid", "operator": "<", "value": "1000" }
     ]
    }
   ]
  },
  {
   "title": "STORAGE STATUS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "FREE iSCSi STORAGE",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "avail" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "storages" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "lvm" }
     ]
    }
   ]
  },
  { "title": "Cluster NYC (Seaborn)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 146 } },
  {
   "title": "USED OF CPU",
   "type": "stat",
   "description": "ALL CPUS ON BOGOTA",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 147 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "PVE001",
     "groupBy": [
      { "params": [ "nodename" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "query": "SELECT mean(\"cpus\") FROM \"system\" WHERE (\"nodename\" = 'pve001-nyc') AND $timeFilter GROUP BY time(10s), \"nodename\" fill(linear)",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=", "value": "pve001-nyc" }
     ]
    },
    {
     "alias": "PVE003",
     "groupBy": [
      { "params": [ "nodename" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=", "value": "pve003-NYC" }
     ]
    }
   ]
  },
  {
   "title": "Total Traffic on Cluster (IN)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "IN",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "nics",
     "select": [
      [
       { "params": [ "netin" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "LXC Containers",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vmid" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "nodename" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "query": "SELECT mean(\"cpus\") AS \"Procesors\", mean(\"maxmem\") /1073741824 AS \"RAM\", max(\"maxdisk\") /1073741824 AS \"DISK\" FROM \"system\" WHERE (\"object\" = 'lxc') AND $timeFilter GROUP BY \"vmid\", \"host\", \"nodename\" LIMIT 1",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Procesors" ], "type": "alias" }
      ],
      [
       { "params": [ "maxmem" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "RAM" ], "type": "alias" }
      ],
      [
       { "params": [ "maxdisk" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "DISK" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "lxc" }
     ]
    }
   ]
  },
  {
   "title": "Total Traffic on Cluster (OUT)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "IN",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "nics",
     "select": [
      [
       { "params": [ "netout" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FREE RAM",
   "type": "stat",
   "description": "Ram FREE per node",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "PVE001",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "memfree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve001-nyc" }
     ]
    },
    {
     "alias": "PVE003",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "memfree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve003-NYC" }
     ]
    }
   ]
  },
  {
   "title": "KVM VPS",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vmid" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "nodename" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "query": "SELECT mean(\"cpus\") AS \"Procesors\", mean(\"maxmem\") /1073741824 AS \"RAM\", max(\"maxdisk\") /1073741824 AS \"DISK\" FROM \"system\" WHERE (\"object\" = 'lxc') AND $timeFilter GROUP BY \"vmid\", \"host\", \"nodename\" LIMIT 1",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Procesors" ], "type": "alias" }
      ],
      [
       { "params": [ "maxmem" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "RAM" ], "type": "alias" }
      ],
      [
       { "params": [ "maxdisk" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "/1073741824" ], "type": "math" },
       { "params": [ "DISK" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "qemu" },
      { "condition": "AND", "key": "vmid", "operator": "<", "value": "1000" }
     ]
    }
   ]
  },
  {
   "title": "TOTAL VPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 155 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vmid" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "select": [
      [
       { "params": [ "vmid" ], "type": "field" },
       { "params": [ " / vmid" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "vmid", "operator": "<", "value": "1000" }
     ]
    }
   ]
  },
  {
   "title": "STORAGE STATUS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "FREE iSCSi STORAGE",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "avail" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "storages" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "lvm" }
     ]
    }
   ]
  }
 ]
}